title: "HostOS Documentation"
repository: cloudlab/hostos-docs/tree/docs-r1 
remote_theme: just-the-docs/just-the-docs

color_scheme: wider

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

footer_content: "Copyright &copy; IBM Corporation 2024."
