title: "HostOS Reports"
repository: cloudlab/hostos-reports/tree/master 
remote_theme: just-the-docs/just-the-docs
color_scheme: wider
aux_links:
    "HostOS Docs ":
        - "https://pages.github.ibm.com/cloudlab/hostos-docs"

footer_content: "Copyright &copy; IBM Corporation 2024."
